name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  image_picker: ^0.8.4+2
  path_provider: ^2.0.1
  gallery_saver:
    git:
      url: https://github.com/dnphawaco/gallery_saver.git
      ref: 5fbb2a409bdf6454f172694957430f1202b63633
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
